version: "3.3"

services:
  workspace:
    image: ${IMAGE:-bresnow/alpnode-wrkspce}:${VERSION:-base}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        #-------------------WEB TERMINAL
        - traefik.http.routers.ttyd-http.rule=Host(`${TTYD_DOMAIN:?SET YOUR VARIABLES}`)
        - traefik.http.routers.ttyd-http.entrypoints=http
        - traefik.http.routers.ttyd-http.middlewares=https-redirect
        - traefik.http.routers.ttyd-https.rule=Host(`${TTYD_DOMAIN:?SET YOUR VARIABLES}`)
        - traefik.http.routers.ttyd-https.entrypoints=https
        - traefik.http.routers.ttyd.service=ttyd
        - traefik.http.routers.ttyd-https.tls=true
        - traefik.http.routers.ttyd-https.tls.certresolver=le
        - traefik.http.services.ttyd.loadbalancer.server.port=8026
        - traefik.http.routers.ttyd.middlewares=admin-auth

          #-------------------FILE SHARE
        - traefik.http.routers.filebrowser-http.rule=Host(`${FILEBROWSER_DOMAIN:?SET YOUR VARIABLES}`)
        - traefik.http.routers.filebrowser-http.entrypoints=http
        - traefik.http.routers.filebrowser-http.middlewares=https-redirect
        - traefik.http.routers.filebrowser-https.rule=Host(`${FILEBROWSER_DOMAIN:?SET YOUR VARIABLES}`)
        - traefik.http.routers.filebrowser-https.entrypoints=https
        - traefik.http.routers.filebrowser.service=filebrowser
        - traefik.http.routers.filebrowser-https.tls=true
        - traefik.http.routers.filebrowser-https.tls.certresolver=le
        - traefik.http.services.filebrowser.loadbalancer.server.port=8021
        - traefik.http.routers.filebrowser.middlewares=admin-auth
    networks:
      - traefik-public
    volumes:
      - 16score13_data:/home
volumes:
  16score13_data:

networks:
  traefik-public:
    external: true
