version: "3.3"

services:
  workspace:
    image: ${IMAGE:-bresnow/alpnode-wrkspce}:${VERSION:-base}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:  

        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        #-------------------WEB TERMINAL
        # SERVICE NAME
        - traefik.http.routers.ttyd.service=ttyd
        # SERVICE ENTRYPOINTS
        - traefik.http.routers.ttyd.entrypoints=https
        # DOMAIN 
        - traefik.http.routers.ttyd.rule=Host(`${TTYD_DOMAIN:?SET YOUR VARIABLES}`)
        # TLS CERTS
        - traefik.http.routers.ttyd.tls=true
        - traefik.http.routers.ttyd.tls.certresolver=le
        # CONTAINER PORT
        - traefik.http.services.ttyd.loadbalancer.server.port=8026
              #-------------------FILE SHARE
        # SERVICE NAME
        - traefik.http.routers.filebrowser.service=filebrowser
        # SERVICE ENTRYPOINTS
        - traefik.http.routers.filebrowser.entrypoints=https
    
        # DOMAIN
        - traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_DOMAIN:?SET YOUR VARIABLES}`)
        # TLS CERTS
        - traefik.http.routers.filebrowser.tls=true
        - traefik.http.routers.filebrowser.tls.certresolver=le
        # CONTAINER PORT
        - traefik.http.services.filebrowser.loadbalancer.server.port=8021
    networks:
      - traefik-public
    volumes:
      - 16score13_band_data:/home
volumes:
  16score13_band_data:

networks:
  traefik-public:
    external: true